### ISSUE TITLE
Help setting up slackbot-tell

### ISSUE THREAD

**Issue by ajmalafif** [stamen/slackbot-tell#5]
Hey all,

I can't tell you how :smiley: i was when I saw this repo! I've tried to set it up and push it to heroku but can't seem to make it work. I know i'm missing something to make this work so I hope someone could point me to the right direction to make this working.

Thanks!

**Comment by mojodna** [comment]
First off, be warned that this is only partially complete (and we don't currently use it).  The main sticking point is that Heroku app idling prevents future deliveries from not necessarily occurring when required.

There are 2 environment variables that need to be set in order for this to even begin to work:

* `SLACK_TOKEN` - this is the web hook token that Slack provides when you configure a new integration
* `REDIS_URL` - a URL for an accessible Redis service (this involves configuring one of the many Heroku Redis add-ons)

Hopefully this will help you get further along.  Please report back and I'll update the docs.

**Comment by ajmalafif** [comment]
Hey there. Thanks for the reply! 

For the record I already set up to `SLACK_TOKEN` but for REDIS_URL, I tried `REDIS_URL` and `REDIS_KEY` since I can't find anything `REDIS_URL` in the code so I thought renaming all the `REDIS_KEY` in the script into `REDIS_URL`.

So basically I actually went through couple trial-and-error but so far can't seem to make it works yet. I'll give it another go and report my findings again.

**Comment by mojodna** [comment]
[redis-url](https://www.npmjs.com/package/redis-url) is used internally, which relies on `REDIS_URL`.

Sounds like the first step is to see whether the service receives data about the slash command and whether it sends a response back.

I just realized that I mis-spoke earlier: it should be configured as a slash command, not a web hook.  I'll update the docs too.

**Comment by ajmalafif** [comment]
That really helps a lot in getting me to understand what's going on. I still haven't manage to figure it out. 

I'll get back at it when I have more time and will share on how to getting this up on heroku when I managed. Thanks again @mojodna you've been very helpful. Appreciate it!

**Comment by pentiumx** [comment]
Hi all. I also wanted to try the script, and I've managed to make it work.
  
It kept showing the `Err invalid db index` error on Heroku even after setting `REDIS_URL`, so I created a Redis client by following [the official instruction](https://devcenter.heroku.com/articles/rediscloud#using-redis-from-node-js) instead of using redis-url.
